[profile.default]
src = "src"
out = "out"
libs = ["lib"]
path = ".env"
chain_id = 10143
metadata = true
metadata_hash = "none"  # disable IPFS
use_literal_content = true  # store source code in JSON

[rpc_endpoints]
monad_testnet = "https://testnet-rpc.monad.xyz"

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = false
quote_style = "double"
sort_imports = true